CREATE TABLE OV_ERROR_LOG (
	ROWID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
	, ERR_STACKTRACE MEDIUMTEXT
	, ERR_MESSAGE MEDIUMTEXT
	, ERR_PARAM MEDIUMTEXT
	, ERR_INSERT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE BATCH_API_CALL_PARAMS (
	BATCH_API_ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT
	, BATCH_API_URL VARCHAR(200) NOT NULL
	, BATCH_API_HTTP_METHOD VARCHAR(200) DEFAULT NULL
	, BATCH_API_CONTENT_TYPE VARCHAR(200) DEFAULT NULL
	, BATCH_API_REQUEST_JSON VARCHAR(3500) NOT NULL
	, BATCH_API_PARAM_HEADER VARCHAR(200) DEFAULT NULL
	, CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
	, UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
